# Generated by Django 4.1.1 on 2023-09-25 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityinventory',
            old_name='last_updated',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='facilityinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='facilityinventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('facility_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.facilityinventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
            ],
        ),
        migrations.AddField(
            model_name='facilityinventory',
            name='products',
            field=models.ManyToManyField(through='database.InventoryItem', to='database.product'),
        ),
    ]
