# Generated by Django 4.1 on 2023-09-25 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_inventoryitem_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityinventory',
            old_name='date',
            new_name='inventory_date',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='database.OrderItem', to='database.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
