# Generated by Django 4.1 on 2023-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_date_facilityinventory_inventory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('naruceno', 'naruceno'), ('poslato', 'poslato'), ('stiglo', 'stiglo')], default='naruceno', max_length=20),
        ),
    ]
