# Generated by Django 4.1 on 2023-09-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
    ]
